Add create site container but should be removed maybe and add override docker compose services

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -15,6 +15,10 @@ services:
         source: sites
         target: /home/frappe/frappe-bench/sites
         volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
+        volume: {}
   configurator:
     command:
       - |
@@ -47,6 +51,10 @@ services:
       - type: volume
         source: sites
         target: /home/frappe/frappe-bench/sites
+        volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
         volume: {}
   db:
     command:
@@ -81,9 +89,9 @@ services:
         condition: service_started
         required: true
     environment:
-      BACKEND: backend:8000
+      BACKEND: ${BACKEND_CONTAINER_NAME}:8000
       CLIENT_MAX_BODY_SIZE: 50m
-      FRAPPE_SITE_NAME_HEADER: frontend
+      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER}
       PROXY_READ_TIMEOUT: "120"
       SOCKETIO: websocket:9000
       UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
@@ -104,6 +112,43 @@ services:
         source: sites
         target: /home/frappe/frappe-bench/sites
         volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
+        volume: {}
+
+  create-site:
+    image: frappe/erpnext:v15.50.0
+    # networks:
+    #   - frappe_network
+    deploy:
+      restart_policy:
+        condition: none
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
   queue-long:
     command:
       - bench
@@ -124,6 +169,10 @@ services:
         source: sites
         target: /home/frappe/frappe-bench/sites
         volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
+        volume: {}
   queue-short:
     command:
       - bench
@@ -143,6 +192,10 @@ services:
       - type: volume
         source: sites
         target: /home/frappe/frappe-bench/sites
+        volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
         volume: {}
   redis-cache:
     image: redis:6.2-alpine
@@ -175,6 +228,10 @@ services:
         source: sites
         target: /home/frappe/frappe-bench/sites
         volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
+        volume: {}
   websocket:
     command:
       - node
@@ -193,6 +250,10 @@ services:
         source: sites
         target: /home/frappe/frappe-bench/sites
         volume: {}
+      - type: volume
+        source: logs
+        target: /home/frappe/frappe-bench/logs
+        volume: {}
 networks:
   default:
     name: frappe_docker_default
@@ -203,6 +264,9 @@ volumes:
     name: frappe_docker_redis-queue-data
   sites:
     name: frappe_docker_sites
+  logs:
+    name: frappe_docker_logs
+
 x-backend-defaults:
   depends_on:
     configurator:
